version: "3"
services:
  portfolio:
    build: .
    restart: always
    networks:
      - generated_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`vasie.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.portfolio-http.rule=Host(`vasie.dev`)"
      - "traefik.http.routers.portfolio-http.entrypoints=web"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"

networks:
  generated_default:
    external: true