services:
  portfolio:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: portfolio
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true