version: '3'

services:
  portfolio:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`vasie.dev`)"  
      - "traefik.docker.network=traefik-public"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.routers.portfolio.service=portfolio"
    networks:
      - traefik-public
    restart: unless-stopped

networks:
  traefik-public:
    external: true