services:
  nodeapp:
    build: 
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodeapp.rule=Host(`vasie.dev`)"
      - "traefik.http.routers.nodeapp.tls=true"
      - "traefik.http.routers.nodeapp.tls.certresolver=letsencrypt"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true