version: "3"

services:
  portfolio:
    build: .
    restart: always
    networks:
      - generated_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`vasie.dev`)"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=acme"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
networks:
  generated_default:
    external: true