version: '3'

services:
  portfolio:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`vasie.dev`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    networks:
      - btcpayserver-docker_default
    restart: unless-stopped

networks:
  btcpayserver-docker_default:
    external: true