version: '3.8'

services:
  portfolio:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    expose:
      - "80"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`vasie.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.middlewares.portfolio-error-pages.errors.status=404"
      - "traefik.http.middlewares.portfolio-error-pages.errors.service=portfolio"
      - "traefik.http.middlewares.portfolio-error-pages.errors.query=/404"
      - "traefik.http.routers.portfolio.middlewares=portfolio-error-pages"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true