version: '3'
services:
  portfolio:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`vasie.dev`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped